from dragonfly import Key

map = {
    "(A|alpha)": Key("a"),
    "(B|bravo) ": Key("b"),
    "(C|charlie) ": Key("c"),
    "(D|delta) ": Key("d"),
    "(E|echo) ": Key("e"),
    "(F|foxtrot) ": Key("f"),
    "(G|golf) ": Key("g"),
    "(H|hotel) ": Key("h"),
    "(I|india|indigo) ": Key("i"),
    "(J|juliet) ": Key("j"),
    "(K|kilo) ": Key("k"),
    "(L|lima) ": Key("l"),
    "(M|mike) ": Key("m"),
    "(N|november) ": Key("n"),
    "(O|oscar) ": Key("o"),
    "(P|papa|poppa) ": Key("p"),
    "(Q|quebec|quiche) ": Key("q"),
    "(R|romeo) ": Key("r"),
    "(S|sierra) ": Key("s"),
    "(T|tango) ": Key("t"),
    "(U|uniform) ": Key("u"),
    "(V|victor) ": Key("v"),
    "(W|whiskey) ": Key("w"),
    "(X|x-ray) ": Key("x"),
    "(Y|yankee) ": Key("y"),
    "(Z|zulu) ": Key("z"),
}
